### ISSUE TITLE
[Feature] please add base58 as well

### ISSUE THREAD

**Issue by rishabhdeepsingh** [HashPals/Name-That-Hash#100]
Add base58 as well to be recognized for hashes. I would like to work on this one.

**Comment by bee-san** [comment]
What do you mean by `add base58`? As in, write a regex for it to identify? Can you give me an example of the input and output you expect?

**Comment by rishabhdeepsingh** [comment]
`Hello` after base58 -> `9Ajdvzr`

**Comment by bee-san** [comment]
Sorry, I really don't understand what you want? 

Perhaps [Ciphey](https://github.com/ciphey/ciphey) is what you want?

https://github.com/ciphey/ciphey

**Comment by rishabhdeepsingh** [comment]
@bee-san Thanks a lot. exactly what I was looking for
