### ISSUE TITLE
Logging does not follow best practises

### ISSUE THREAD

**Issue by bee-san** [HashPals/Name-That-Hash#33]
When calling the API, the caller's logging module will be disabled :-(

I don't know how to fix this.

**Comment by ShubhamPalriwala** [comment]
Hey @bee-san , can you elaborate a bit further on this please !

**Comment by bee-san** [comment]
> Hey @bee-san , can you elaborate a bit further on this please !

Hey!

Thanks for commenting. We fixed this by not using the library causing this :D
