### ISSUE TITLE
[CRASH] greppable (macOS 11.2.1)

### ISSUE THREAD

**Issue by JayBrown** [HashPals/Name-That-Hash#34]
Tried the `-g` greppable option on macOS 11.2.1 (Big Sur, Intel, nth installed with Homebrew), but getting a crash. Below is the stderr when trying to detect an IPFS multihash. Crash also happens with "regular" hashes like MD5.

```
nth -t 'QmPikdNwuAATbEM7adqBhy5sLGiVk19x7gUbY6LDioACHY' -g
Traceback (most recent call last):
  File "/usr/local/bin/nth", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/name-that-hash/1.1.0/libexec/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/name-that-hash/1.1.0/libexec/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/name-that-hash/1.1.0/libexec/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/name-that-hash/1.1.0/libexec/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/name-that-hash/1.1.0/libexec/lib/python3.9/site-packages/name_that_hash/runner.py", line 124, in main
    print(pretty_printer.greppable_output(output))
  File "/usr/local/Cellar/name-that-hash/1.1.0/libexec/lib/python3.9/site-packages/name_that_hash/prettifier.py", line 36, in greppable_output
    outputs_as_dict.update(i[0].hash_obj)
TypeError: 'HashType' object is not subscriptable
```

**Comment by bee-san** [comment]
Thanks for this! I can recreate this, will fix as soon as my dinner is ready 🥐 Thank you SO much for reporting this!! Imagine if you hadn't hahaha!

**Comment by bee-san** [comment]
This is caused because `greppable_output` in the `prettifier` class is doing 2 things:
1. Handling the case of 1 hash
2. Handling the case of many hashes

I think I can fix this by making 1 hash into a list and putting that into there, but I'd have to do some heavy testing to make sure it's fixed :D

**Comment by bee-san** [comment]
Nevermind, all the CI ran and I couldn't break it -- I guess the easy solution is the solution!

**Comment by harens** [comment]
> on macOS 11.2.1 (Big Sur, Intel, nth installed with Homebrew)

Glad to see someone's already using the new Homebrew formula. You'll be glad to know that there's already a PR to bump it to the new update: https://github.com/Homebrew/homebrew-core/pull/71222

**Comment by bee-san** [comment]
![image](https://user-images.githubusercontent.com/10378052/108001317-fdb9be80-6fe3-11eb-96d6-bfddc84ec15f.png)

Just to confirm:

I took the output of this and placed it into a JSON validator, it's valid JSON so everything is working :D

**Comment by harens** [comment]
With Homebrew, the CLT works fine. It's just the python module only works on MacPorts.

**Comment by bee-san** [comment]
@harens that's now a comment in the README :))) 

https://github.com/HashPals/Name-That-Hash#-installation

**Comment by alebcay** [comment]
Just FYI @harens and @bee-san, with https://github.com/Homebrew/homebrew-core/pull/71243, the Python module would also become available when installing via Homebrew.

**Comment by harens** [comment]
Thanks a a lot @alebcay! I wasn't sure how to get it working so thank you putting the time into doing that.
