### ISSUE TITLE
'base64' in self.kwargs is always True

### ISSUE THREAD

**Issue by glozanoa** [HashPals/Name-That-Hash#52]
https://github.com/HashPals/Name-That-Hash/blob/5290d8c221728a8ebe48f05d8fbb3b59b867b6c3/name_that_hash/check_hashes.py#L27

'base64' in self.kwargs is always True, no matter that the value of the 'base64' key in self.kwargs dictionary is False or True.

**Comment by bee-san** [comment]
All of our tests fail with just that code change, so I've updated it to feature an "and" :)
