### ISSUE TITLE
Cant find Kerberos 5 TGS-REP etype 23

### ISSUE THREAD

**Issue by keldnorman** [HashPals/Name-That-Hash#53]
My hash is from a Kerberosting session.. it looks like this: 

$krb5tgs$23$*Administrator$domain$Svc/host.local:$krb5tgs$23$1433*$13371337133713371337133713371337$xxxxxxxxx-892chars-after-the-$-xxxxxx

Why cant Name-That-Hash not tell me it is a Kerberos 5 TGS-REP etype 23 ( hashcat number 13100 ) type of hash ? 

- - - - - - 
root@gateway:~/Redteam/4.Hash# name-that-hash --text --no-banner '$krb5tgs$23$*Administrator$domain$Svc/host.local:$krb5tgs$23$1433*$13371337133713371337133713371337$xxxxxxxxx-$here-is-892-chars-letters-and-numbers'

$krb5tgs$23$*Administrator$domain$Svc/host.local:$krb5tgs$23$1433*$13371337133713371337133713371337$..REDACTEC..
No hashes found.
- - - - - -

**Comment by bee-san** [comment]
We can't find it because we don't support it _yet_. I'll add it now :)

https://github.com/hashcat/hashcat/issues/1707
