### ISSUE TITLE
Scrape Hashcat website to find out what hashes we are missing

### ISSUE THREAD

**Issue by bee-san** [HashPals/Name-That-Hash#60]
We are missing some hashes from the Hashcat example hashes page:
https://hashcat.net/wiki/doku.php?id=example_hashes

I propose we:
1. Scrape that page for every `Hash-Name`
2. Check to see if `Hash-Name` is in this file https://github.com/HashPals/Name-That-Hash/blob/main/name_that_hash/hashes.py
3. If it's not in the file, append it to a new file.

Post the file here so we know what we need to add.

This is issue is suitable for beginners :) 

**Note: You do not have to create the Regex. Just find out what hashes are not in the database**

If you need support, come to the [Discord](HTTP://discord.skerritt.blog)

**Comment by bee-san** [comment]
Edit: This is taken by someone :)

**Comment by JabbaCS** [comment]
This is all the hashes missed in the specified format.
Some hashes may be duplicates due to the algorithm I was using, accuracy can be increased if required.

[format_missed.txt](https://github.com/HashPals/Name-That-Hash/files/6150600/format_missed.txt)
