### ISSUE TITLE
Write a script to turn DataClass into JSON 

### ISSUE THREAD

**Issue by bee-san** [HashPals/Name-That-Hash#71]
Turn all the `DataClass`'s in this file:
https://github.com/HashPals/Name-That-Hash/blob/main/name_that_hash/hashes.py

Into JSON with this format:
https://github.com/psypanda/hashID/blob/master/prototypes.json

Please submit a PR to the repo with your script :)

**Comment by bburky** [comment]
I've forgotten the full history of `prototypes.json`. At one point I played with the idea of moving the hash definitions completely out of Python and into JSON, but we never finished it: https://github.com/psypanda/hashID/pull/30

I'm not really sure if that's better or not than having it in Python.

I've also forgotten how wet generated it. I'm pretty sure it was just a python `json.dump()` of the data. You may need to do something like this to dump dataclasses:
https://stackoverflow.com/a/51286749

**Comment by bee-san** [comment]
> I've forgotten the full history of `prototypes.json`. At one point I played with the idea of moving the hash definitions completely out of Python and into JSON, but we never finished it: [psypanda/hashID#30](https://github.com/psypanda/hashID/pull/30)
> 
> I'm not really sure if that's better or not than having it in Python.
> 
> I've also forgotten how we generated it. I'm pretty sure it was just a python `json.dump()` of the data. You may need to do something like this to dump dataclasses:
> https://stackoverflow.com/a/51286749

This is purely for inter-language operability 😅 I'm working on a project in Go and can't use the DB here unless it's in a text-file based format (such as JSON)

I feel like this app is 2 parts:
1. The database
2. The CLI / API in Python

If we can export to JSON, it means other languages can use it and that means we can get more contributors.

I was playing around with the idea of having the database be a Git submodule, but I don't see why a JSON export wouldn't work for what I'm imagining :)

**Comment by Jayy001** [comment]
Hi bee, here you go:

```py
return_value = []

for prototype in prototypes:
    return_value.append(
        {
            "regex": str(prototype.regex.pattern),
            "modes": [asdict(i) for i in prototype.modes],
        }
    [)](url)

print(json.dumps(return_value, indent=4))
```

[hashes.txt](https://github.com/HashPals/Name-That-Hash/files/6175775/hashes.txt)

add this to the end of the hashes.py and run it. Ill put the json attached

**Comment by bee-san** [comment]
> Hi bee, here you go:
> 
> ```python
> import json
> 
> return_value = []
> 
> for prototype in prototypes:
>     return_value.append(
>         {
>             "regex": str(prototype.regex.pattern),
>             "modes": [asdict(i) for i in prototype.modes],
>         }
>     )
> 
> with open("result.txt", "w") as file:
>     file.write(json.dumps(return_value, indent=4))
> ```
> 
> [hashes.txt](https://github.com/HashPals/Name-That-Hash/files/6175775/hashes.txt)
> 
> add this to the end of the hashes.py and run it. Ill put the json attached

Why are all the dollar signs escaped?

**Comment by Jayy001** [comment]
What do you mean by this? I can't see it

**Comment by bee-san** [comment]
Open the file
![image](https://user-images.githubusercontent.com/10378052/111881423-3adcec00-89a8-11eb-9ea3-3a9f02c7b806.png)

**Comment by bee-san** [comment]
Ah wait that's the regex itself nvm

**Comment by Jayy001** [comment]
Ahh no worries 😄
